### ISSUE TITLE
Error calling get_status() on IdMappingClient request

### ISSUE THREAD

**Issue by hlfernandez** [multimeric/Unipressed#21]
Hello there, 

I am using the example given in the main README to get the ID mappings:
```
from unipressed import IdMappingClient
request = IdMappingClient.submit(
    source="UniProtKB_AC-ID", dest="Gene_Name", ids={"A1L190", "A0JP26", "A0PK11"}
)
list(request.each_result())
```

But I want to check the status before obtaining the results, so I call` request.get_status()` and obtain the following error:
```

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.10/dist-packages/unipressed/id_mapping/core.py", line 52, in get_status
    return requests.get(
KeyError: 'jobStatus'
```

I hope you can help me to know what I am doing wrong.

**Comment by multimeric** [comment]
Hi, thanks for the issue. Unfortunately this actually seems to be a bug on the UniProt end. If the job has finished, UniProt won't give us a job status for some reason. In any case, I'll write a workaround for this strange behaviour.

**Comment by hlfernandez** [comment]
Alright, I will wait for the workaround then :-) I am creating a Docker image with [Unipressed](https://github.com/multimeric/Unipressed) installed and with a simple script that accepts a list of accession numbers and produces the corresponding mappings. It would be nice if your library has a method to check for valid from and to pairs (https://rest.uniprot.org/configure/idmapping/fields).

**Comment by multimeric** [comment]
Well Unipressed does actually validate the correct to and from pairs, but it does so using *static typing*, so you'll only notice the checking if you use mypy/pydantic etc *or* you use an IDE that has a built-in type checker like PyCharm or VS Code. If that doesn't fit your use case, and you're after runtime type checking, then I'll open a separate issue for that, since it may be possible using pydantic etc.
